FROM alpine:latest

RUN apk add --update --no-cache \
  # Build dependencies
  git \
  gcc \
  clang \
  make \
  samurai \
  cmake \
  # Dev tools
  openssh \
  openssl \
  gcompat \
  gdb \
  clang-extra-tools \
  lldb \
  cppcheck \
  valgrind \
  doxygen 
