FROM archlinux:base-devel

RUN pacman -Syu  --noconfirm \
    # Build dependencies
    git \
    gcc \
    clang \
    make \
    ninja \
    cmake \
    # Dev tools
    gdb \
    lldb \
    cppcheck \
    valgrind \
    doxygen \
    && pacman -Scc --noconfirm
