#include "Game.h"

#include <iostream>
#include <string>

#include "Art.h"
#include "Main Menu.h"
#include "Room Controller.h"

using std::cin;
using std::cout;
using std::string;

void Game::start()
{
  // Seed the random number generator
  std::srand(std::time(nullptr));

  // I use a rand() here because the first value generated by rand() after srand() seems to be consistently increasing if the rand() bounds are large enough
  std::rand(); // rand range formula: min + (rand() % ((max + 1) - min))

  // Menu Art
  mainMenu();

  // These variables will be constantly tracked / updated while the game is played
  player = new Player;

  // Generates the map with rooms to traverse
  map = new Map;
}

void Game::end()
{
  // Print game results
  if (winCondition)
    victoryArt(player);
  else
    gameOverArt(player);

  // Free memory
  delete player;
  delete map;

  // Pause the end screen until the user is ready to close the application
  cout << "Press enter to exit the program: ";
  string enterKey = " ";
  getline(cin, enterKey);
  cout << "\n";
}

void Game::loop()
{
  if(!roomController(player, map))
    running = false;
}
