name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Windows Binary
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile.desktop
          target: export-windows
          outputs: type=local,dest=build/out
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Linux Binary
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile.desktop
          target: export-linux
          outputs: type=local,dest=build/out
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload Release Assets
        run: gh release upload "${{ github.ref_name }}" "build/out/ddd.exe" "build/out/ddd.AppImage"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: images.cloudisms.dev
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile.prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            images.cloudisms.dev/dastardly-dungeon-dwellers:${{ github.ref_name }}
            images.cloudisms.dev/dastardly-dungeon-dwellers:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Disabled on cloudflare free plan
          # cache-from: type=registry,ref=images.cloudisms.dev/dastardly-dungeon-dwellers:buildcache
          # cache-to: type=registry,ref=images.cloudisms.dev/dastardly-dungeon-dwellers:buildcache,mode=max
